spring:
  data:
    elasticsearch:
      cluster-name: [集群名称] #默认为elasticsearch
      cluster-nodes: [主机地址]:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      properties:
        path:
          logs: /home/elsearch/logs #elasticsearch日志存储目录
          data: /home/elsearch/data #elasticsearch数据存储目录
